// The watchdog simulator's whole personality lives in this one reviewable
// config. Spine 3 needs months of ticket history to score and the network has
// run for days, so the history is synthetic, generated by simulate.ts,
// stored with data_source = 'synthetic', and disclosed in the register and
// the dataset statement. Every number below is a parameter to sanity check
// with Mhofu, not a claim about Harare: only the fare (150 cents, the real
// flat corridor fare from the 2026-07-07 fieldwork seed) is a measured fact.

export interface LeakBand {
  /** Fraction of the targeted tickets that go unrecorded, drawn uniformly. */
  min: number;
  max: number;
}

export interface WatchdogConfig {
  /** Synthetic kombis. Labels only; the real fleet table is never touched. */
  vehicleLabels: string[];
  /** Days of history to generate, ending on the requested end day. */
  historyDays: number;
  /** Flat corridor fare in USD cents (real, from the seeded fare data). */
  fareCents: number;
  /** Seats per kombi. */
  seats: number;
  /** One way legs worked per vehicle per day (a round trip is two legs). */
  weekdayLegs: number;
  weekendLegs: number;
  /** Mean fraction of seats filled per leg, plus a uniform jitter band. */
  weekdayLoad: number;
  weekendLoad: number;
  loadJitter: number;
  /** Mean fraction of fares paid digitally, plus jitter. */
  digitalShare: number;
  digitalJitter: number;
  /** Mean fraction of a day's fares that land in rush hours, plus jitter. */
  peakShare: number;
  peakJitter: number;
  /** Probability that a route day carries injected leakage. */
  leakRate: number;
  /** Probability that a leak day hits two vehicles instead of one. */
  twoVehicleLeakRate: number;
  /** heavy_skim: this share of a vehicle's cash fares goes unrecorded. */
  heavySkim: LeakBand;
  /** peak_skim: this share of a vehicle's rush hour fares goes unrecorded. */
  peakSkim: LeakBand;
  /** short_day: recording stops mid afternoon; this share of the whole day
   *  (cash and digital alike) never gets written down. */
  shortDay: LeakBand;
}

export const DEFAULT_WATCHDOG_CONFIG: WatchdogConfig = {
  vehicleLabels: ["Kombi A", "Kombi B", "Kombi C", "Kombi D"],
  historyDays: 90,
  fareCents: 150,
  seats: 16,
  weekdayLegs: 20,
  weekendLegs: 14,
  weekdayLoad: 0.72,
  weekendLoad: 0.58,
  loadJitter: 0.1,
  digitalShare: 0.35,
  digitalJitter: 0.08,
  peakShare: 0.45,
  peakJitter: 0.06,
  leakRate: 0.08,
  twoVehicleLeakRate: 0.15,
  heavySkim: { min: 0.3, max: 0.5 },
  peakSkim: { min: 0.45, max: 0.65 },
  shortDay: { min: 0.35, max: 0.45 },
};
