-- 0020 watchdog synthetic history
-- Spine 3, the revenue watchdog, needs months of ticket history to score and
-- the network has run for days, not months. These tables hold a clearly
-- labelled synthetic history generated by services/spine/src/watchdog (the
-- generator config is committed and reviewable). Every row carries
-- data_source = 'synthetic'; nothing here ever mixes with the real ledger,
-- which stays the only source of real money numbers.
--
-- Unlike tickets and ledger rows these are derived, recomputable data, so
-- there is deliberately no append only trigger: the simulator may wipe and
-- regenerate its own synthetic rows. Only the service role can write
-- (no insert/update/delete policies exist); owners read their own rows.

-- Per vehicle per day ticket history, straight out of the simulator.
create table public.watchdog_vehicle_days (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.owners (id) on delete cascade,
  route_id uuid not null references public.routes (id) on delete cascade,
  -- synthetic vehicles are labels, not rows in public.vehicles: the real
  -- fleet table never holds invented kombis
  vehicle_label text not null,
  day date not null,
  tickets integer not null check (tickets >= 0),
  digital_tickets integer not null check (digital_tickets >= 0),
  peak_tickets integer not null check (peak_tickets >= 0),
  gross_cents integer not null check (gross_cents >= 0),
  data_source text not null default 'synthetic'
    check (data_source = 'synthetic'),
  -- ground truth of what the generator injected, kept for honest evaluation
  -- and the dataset statement; null means a clean day
  injected_leakage text
    check (injected_leakage in ('heavy_skim', 'peak_skim', 'short_day')),
  created_at timestamptz not null default now(),
  check (digital_tickets <= tickets),
  check (peak_tickets <= tickets),
  unique (owner_id, route_id, vehicle_label, day)
);

alter table public.watchdog_vehicle_days enable row level security;

create policy "watchdog vehicle days select own fleet"
  on public.watchdog_vehicle_days for select
  to authenticated
  using (owner_id = (select private.current_owner_id()));

-- Per route per day verdicts: features, score, and the bilingual explanation.
-- The explanation describes patterns only; the narrator that writes it has no
-- person fields in its input (proven by unit test in services/spine).
create table public.watchdog_day_flags (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.owners (id) on delete cascade,
  route_id uuid not null references public.routes (id) on delete cascade,
  day date not null,
  tickets integer not null check (tickets >= 0),
  tickets_ratio numeric not null,
  peak_share numeric not null,
  digital_share numeric not null,
  worst_vehicle_ratio numeric not null,
  score numeric not null,
  flagged boolean not null,
  -- which detector produced the verdict; serving follows the committed
  -- watchdog metrics verdict, exactly like Spine 1
  engine text not null check (engine in ('threshold:v1', 'forest:v1')),
  explanation_en text,
  explanation_sn text,
  data_source text not null default 'synthetic'
    check (data_source = 'synthetic'),
  injected_leakage text
    check (injected_leakage in ('heavy_skim', 'peak_skim', 'short_day')),
  created_at timestamptz not null default now(),
  unique (owner_id, route_id, day)
);

alter table public.watchdog_day_flags enable row level security;

create policy "watchdog day flags select own fleet"
  on public.watchdog_day_flags for select
  to authenticated
  using (owner_id = (select private.current_owner_id()));
