// Trains and evaluates Spine 1 against the real segment_times in the
// database, then writes the verdict where serving code can read it:
//
//   services/spine/metrics/metrics.json   the machine readable verdict
//   services/spine/metrics/METRICS.md     the human readable table
//
// Reads public data with the anon key only. Usage:
//
//   pnpm spine:train                       # HEIGHTS-REZENDE, real rides
//   pnpm spine:train -- --route CODE --source real_field_ride

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { anonClient, loadRouteData } from "./data.ts";
import { buildMetrics, evaluateLeaveOneJourneyOut, type Metrics } from "./train.ts";
import { loadRepoEnv } from "../lib/env.ts";

loadRepoEnv();

const spineRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const METRICS_DIR = join(spineRoot, "metrics");

function parseArgs(argv: string[]): { routeCode: string; dataSource: string } {
  const args = { routeCode: "HEIGHTS-REZENDE", dataSource: "real_field_ride" };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--route") args.routeCode = argv[++i] ?? args.routeCode;
    else if (argv[i] === "--source") args.dataSource = argv[++i] ?? args.dataSource;
  }
  return args;
}

function scorerLine(s: { maeSeconds: number | null; predictions: number }): string {
  if (s.maeSeconds === null) return "no predictions";
  return `${s.maeSeconds} s over ${s.predictions} predictions`;
}

function verdictSentence(m: Metrics): string {
  switch (m.verdict) {
    case "insufficient_data":
      return (
        `${m.journeys} recorded ${m.journeys === 1 ? "journey is" : "journeys are"} not enough ` +
        `to trust any evaluation (the rule requires ${m.minJourneysForPromotion}), so the ` +
        `baseline serves and every rendered estimate says how many rides it stands on.`
      );
    case "baseline":
      return (
        `The model did not beat the baseline on held out journeys, so the baseline keeps ` +
        `serving. A model earns its place with evidence or not at all.`
      );
    case "promoted":
      return (
        `The model beat the baseline on held out journeys with at least ` +
        `${m.minJourneysForPromotion} recorded, so model:v1 serves.`
      );
  }
}

function renderMarkdown(m: Metrics): string {
  return `# Spine 1 arrival prediction: evaluation

Generated by \`pnpm spine:train\` at ${m.generatedAt}. Method: leave one
journey out. Every journey is held out in turn, both scorers are fit on the
remaining journeys, and mean absolute error is measured on the held out
segment durations. Route ${m.routeCode}, data source ${m.dataSource}.

| Measure | Value |
| --- | --- |
| Recorded journeys | ${m.journeys} |
| Segment observations | ${m.segments} |
| Baseline, per segment average (the named naive average) | ${scorerLine(m.baseline)} |
| Model, per segment per hour average | ${scorerLine(m.model)} |
| Verdict | ${m.verdict} |
| Served engine | ${m.served} |

## The promotion rule

The model serves only when there are at least ${m.minJourneysForPromotion}
recorded journeys AND it beats the baseline on held out data. The rule lives
in \`src/eta/train.ts\` and serving code reads only the verdict in
\`metrics.json\`; nothing else decides. The promotion path itself is proven in
\`test/eta-train.test.ts\` on a synthetic rush hour fixture where the model
wins and is promoted.

## Verdict

${verdictSentence(m)}
`;
}

const args = parseArgs(process.argv.slice(2));
const data = await loadRouteData(anonClient(), args.routeCode, args.dataSource);
if (!data) {
  console.error(`route ${args.routeCode} not found`);
  process.exit(2);
}

const report = evaluateLeaveOneJourneyOut(data.observations);
const metrics = buildMetrics(report, {
  routeCode: args.routeCode,
  dataSource: args.dataSource,
  generatedAt: new Date().toISOString(),
});

mkdirSync(METRICS_DIR, { recursive: true });
writeFileSync(join(METRICS_DIR, "metrics.json"), JSON.stringify(metrics, null, 2) + "\n");
writeFileSync(join(METRICS_DIR, "METRICS.md"), renderMarkdown(metrics));

console.log(
  `${metrics.routeCode}: ${metrics.journeys} journeys, ${metrics.segments} segments | ` +
    `baseline MAE ${scorerLine(metrics.baseline)} | model MAE ${scorerLine(metrics.model)} | ` +
    `verdict ${metrics.verdict}, serving ${metrics.served}`,
);
console.log(`wrote metrics/metrics.json and metrics/METRICS.md`);
